import {useCallback,useEffect,useState} from 'react';
import TripForm from './TripForm';
import TripMap from './TripMap';
import ChatPanel from './ChatPanel';
import {api} from './types';
import type {Plan} from './types';

export default function App(){
  const [plan,setPlan]=useState<Plan|null>(null),[trip,setTrip]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fixture,setFixture]=useState<boolean|null>(null),[selected,setSelected]=useState(''),[shared,setShared]=useState(''),[readonly,setReadonly]=useState(false),[clarifications,setClarifications]=useState<string[]>([]),[view,setView]=useState<'form'|'chat'>('form'),[routeChoice,setRouteChoice]=useState(0);
  useEffect(()=>{api<{fixture_mode:boolean}>('/health').then(h=>setFixture(h.fixture_mode)).catch(()=>setError('Backend unavailable. Start FastAPI on port 8000.'));
    const token=new URLSearchParams(location.search).get('share');
    if(token)api<{current:Plan}>('/trips/shared/'+encodeURIComponent(token)).then(t=>{setPlan(t.current);setReadonly(true);}).catch(e=>setError(e.message));
  },[]);
  const select=useCallback((id:string)=>{setSelected(id);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'center'});},[]);
  async function action(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
  async function buildPlan(request:unknown,routeOption=0){const t=await api<{id:string}>('/trips','POST',request);setTrip(t.id);setRouteChoice(routeOption);const result=await api<{version:Plan}>('/trips/'+t.id+'/plan','POST',{route_option:routeOption});setPlan(result.version);setShared('');}
  function create(request:unknown){void action(async()=>{setClarifications([]);await buildPlan(request);});}
  function useRoute(i:number){if(!trip)return;void action(async()=>{setRouteChoice(i);const result=await api<{version:Plan}>(`/trips/${trip}/plan`,'POST',{route_option:i});setPlan(result.version);setShared('');});}
  function intake(message:string){void action(async()=>{const result=await api<{request:unknown|null;clarifications:string[]}>('/trips/intake','POST',{message});setClarifications(result.clarifications);if(result.request)await buildPlan(result.request);});}
  function patch(id:string,status:string){void action(async()=>{const r=await api<{version:Plan}>(`/trips/${trip}/activities/${id}`,'PATCH',{status});setPlan(r.version);});}
  function delay(){void action(async()=>{const r=await api<{version:Plan}>(`/trips/${trip}/replan`,'POST',{delay_minutes:90});setPlan(r.version);});}
  function share(){void action(async()=>{const r=await api<{share_url:string}>(`/trips/${trip}/share`,'POST');setShared(location.origin+'/?share='+r.share_url.split('/').pop());});}
  return <><header className="site-header"><a className="brand" href="/"><span className="brand-mark" aria-hidden="true"/>TripPilot<span>INDIA</span></a><span className="header-note">THE ROAD, WELL PLANNED.</span><nav className="header-links"><a href="#planner">Planner</a><a href="https://github.com/praneeth-7606/trippilot-india">Project ↗</a></nav></header>
    <main id="planner"><section className="intro"><div className="intro-copy"><span className="eyebrow pill">ROAD TRIPS / GROUP PLANNING</span><h1>Good trips leave<br/>room for the journey.</h1><p>Plan the ride, the stops, and the time to actually enjoy them. An editable itinerary built around your group — with route evidence, honest conflicts, and a shareable plan.</p><ul className="feature-pills"><li>Two-wheeler or driving routes</li><li>Meals, rest and washroom candidates</li><li>Time conflicts and source evidence</li></ul></div><div className="journey-card" aria-label="Featured trip: Coimbatore to Munnar and back"><span>THIS WEEKEND’S CIRCUIT</span><strong>Coimbatore <i>↗</i> Munnar</strong><p>6 friends · 3 motorcycles · 2 days</p><div className="journey-line" aria-hidden="true"><span className="stop"><span className="dot"/>START</span><span className="track"><span className=" mover"/></span><span className="stop"><span className="dot"/>THE HILLS</span><span className="track"><span className="mover"/></span><span className="stop"><span className="dot"/>HOME</span></div><small>Includes outbound + return travel</small></div></section>
      <div className={'notice'+(fixture===null?' is-loading':'')} role="status"><span className="notice-dot" aria-hidden="true"/>{fixture===null?'Checking data connection…':fixture?'SYNTHETIC DEMO DATA · Routes, listings, hours and weather are illustrative. Add your SerpApi key for live searches.':'LIVE SEARCH MODE · Results remain estimates, not confirmed reservations.'}</div>
      {error&&<div className="error" role="alert">{error}</div>}
      {busy&&<div className="loading-bar" role="status" aria-label="Building your itinerary"><span/></div>}
      <div className="workspace">{!readonly&&<div className="planner-side"><div className="view-toggle" role="tablist" aria-label="Planner input"><button role="tab" aria-selected={view==='form'} className={view==='form'?'pill-btn active':'pill-btn'} onClick={()=>setView('form')}>Route form</button><button role="tab" aria-selected={view==='chat'} className={view==='chat'?'pill-btn active':'pill-btn'} onClick={()=>setView('chat')}>Vacation chat</button></div>{view==='form'?<TripForm busy={busy} onPlan={create} onIntake={intake} clarifications={clarifications}/>:<ChatPanel onBuild={create}/>}</div>}
      <section className="results" aria-live="polite" aria-busy={busy}>
      {!plan?<div className="empty"><span className="eyebrow">02 / YOUR ITINERARY</span><h2>A little structure.<br/>A lot more freedom.</h2><p>Choose your dates and constraints. We’ll make room for breaks, check the return journey, and explain what fits.</p><div className="empty-cards"><div><strong>Route-first</strong><span>Outbound + return checked</span></div><div><strong>Honest conflicts</strong><span>What fits, what doesn’t</span></div><div><strong>Shareable</strong><span>Read-only trip link</span></div></div><small>Fixture mode supports Coimbatore ↔ Munnar. Other routes require a live key.</small></div>:<>
        <div className="plan-heading"><div><span className="eyebrow">02 / YOUR ITINERARY · VERSION {plan.version}</span><h2>Your journey, mapped out.</h2></div><span className={'badge '+plan.status}><span className="badge-dot" aria-hidden="true"/>{plan.status}</span></div>
        <div className="toolbar">{!readonly&&<><button className="pill-btn" disabled={busy} onClick={delay}>We’re 90 minutes late</button><button className="pill-btn" disabled={busy} onClick={share}>Share read-only trip</button></>}<button className="pill-btn ghost" onClick={()=>window.print()}>Print summary</button></div>
        {shared&&<p className="share">Read-only link: <a href={shared}>{shared}</a></p>}
        {plan.route&&<><div className="metrics"><div className="stat"><span className="stat-label">Outbound distance</span><strong>{plan.route.total_distance_km} km</strong><span className="stat-sub">Verified road stops</span></div><div className="stat"><span className="stat-label">Drive time</span><strong>{Math.round(plan.route.total_duration_min/60*10)/10} h</strong><span className="stat-sub">Before breaks</span></div><div className="stat"><span className="stat-label">Partial cost / person</span><strong>₹{plan.budget?.per_person_inr.toLocaleString('en-IN')}</strong><span className="stat-sub">Fuel + food + estimates</span></div></div><div className="map-wrap"><TripMap plan={plan} onSelect={select}/><span className="map-legend">Animated route preview · schematic waypoints</span></div><p className="map-note">Dashed line connects route waypoints; it is not road-accurate geometry. Verify motorcycle mode in your navigation app.</p></>}
        {plan.issues.length>0&&<div className="warnings"><h3>Check before you go</h3>{plan.issues.map((i,index)=><p key={index}><strong>{i.severity.toUpperCase()} · </strong>{i.message}</p>)}</div>}
        {plan.days.map((day,index)=><section className="day" key={day.day}><div className="day-title"><span className="day-number">{String(index+1).padStart(2,'0')}</span><div><h3>{new Date(day.day+'T12:00:00').toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</h3><span>Asia/Kolkata · {day.activities.length} scheduled items</span></div></div><ol className="timeline">{day.activities.map(a=><li id={a.id} className={(selected===a.id?'selected ':'')+a.status} key={a.id}><div className="time">{a.planned_start.slice(0,5)}<small>{a.planned_end.slice(0,5)}</small></div><div className="activity-card"><span className={'activity-type '+a.type}>{a.type} · {a.status}</span><h4>{a.name}</h4><p>{a.explanation}</p><div className="activity-actions">{!readonly&&<><button disabled={busy} onClick={()=>patch(a.id,a.status==='locked'?'planned':'locked')}>{a.status==='locked'?'Unlock':'Lock'}</button><button disabled={busy||a.status==='locked'} onClick={()=>patch(a.id,a.status==='skipped'?'planned':'skipped')}>{a.status==='skipped'?'Restore':'Skip'}</button></>}<details><summary>Sources & estimates</summary>{a.sources.map((s,i)=><p key={i}>{s.kind} · {s.engine||'Python calculation'} · {new Date(s.retrieved_at).toLocaleString('en-IN')}<br/>{s.note}{s.url&&<><br/><a href={s.url} target="_blank" rel="noreferrer">View source ↗</a></>}</p>)}</details></div></div></li>)}</ol></section>)}
        {plan.route_alternatives.length>0&&<div className="route-options"><h3>Available routes — pick one</h3><ol>{[{label:'Recommended route',total_distance_km:plan.route?.total_distance_km||0,total_duration_min:plan.route?.total_duration_min||0},...plan.route_alternatives].map((r,i)=><li key={i} className={routeChoice===i?'chosen':''}><span><strong>{r.label}</strong> · {r.total_distance_km} km · {Math.round(r.total_duration_min/60*10)/10} h</span>{!readonly&&(routeChoice===i?<span className="chosen-badge">In use</span>:<button className="pill-btn" disabled={busy} onClick={()=>useRoute(i)}>Use this route</button>)}</li>)}</ol><small>Choosing a route rebuilds stops, stays and costs around it.</small></div>}
        <details className="support"><summary>Route alternatives, costs & weather</summary>{plan.route_alternatives.map((r,i)=><p key={i}>{r.label}: {r.total_distance_km} km · {r.total_duration_min} min (outbound)</p>)}{plan.budget?.lines.map((l,i)=><p key={i}>{l.category}: ₹{l.amount_inr.toLocaleString('en-IN')} — {l.basis}</p>)}{plan.weather.map((w,i)=><p key={w.day+'-'+i}>{w.day}: {w.summary}</p>)}{plan.route?.legs.map((l,i)=>l.navigation_url&&<a key={i} href={l.navigation_url} target="_blank" rel="noreferrer">Open navigation ↗</a>)}</details>
        <details className="support"><summary>What didn’t fit & planning assumptions</summary>{plan.excluded.map((a,i)=><p key={i}><strong>{a.name}</strong> — {a.reason}</p>)}{plan.notes.map((n,i)=><p key={i}>{n}</p>)}{plan.advisories.map((a,i)=><p key={i}>{a.text} {a.url&&<a href={a.url} rel="noreferrer" target="_blank">Official information ↗</a>}</p>)}</details>
      </>}
      </section></div></main><footer>TripPilot India · Phase 1 preview <span>Built with SerpApi · Deterministic scheduling</span></footer></>;
}
